include ':vector'
include ':realmfieldnameshelper'
include ':span'
include ':textdrawable'
include ':autocomplete'
include ':matrix-sdk-android'
include ':matrix-sdk-android-rx'
include ':diff-match-patch'
include ':attachment-viewer'
include ':multipicker'
include ':library:ui-styles'
include ':dialpad'
include ':matrix-sdk-android-flow'
