include ':vector'
include ':vector-config'
include ':library:external:textdrawable'
include ':library:external:span'
include ':matrix-sdk-android'
include ':library:core-utils'
include ':library:ui-styles'
include ':library:jsonviewer'
include ':library:attachment-viewer'
include ':library:diff-match-patch'
include ':library:multipicker'
include ':library:external:realmfieldnameshelper'
include ':library:dialpad'
include ':matrix-sdk-android-flow'
